/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { KeyboardControls } from "@react-three/drei";

import Ecctrl, { EcctrlAnimation } from "ecctrl";
type GLTFResult = GLTF & {
  nodes: {
    BaseHuman_1: THREE.SkinnedMesh;
    BaseHuman_2: THREE.SkinnedMesh;
    BaseHuman_3: THREE.SkinnedMesh;
    BaseHuman_4: THREE.SkinnedMesh;
    BaseHuman_5: THREE.SkinnedMesh;
    BaseHuman_6: THREE.SkinnedMesh;
    Bone: THREE.Bone;
  };
  materials: {
    Shirt: THREE.MeshStandardMaterial;
    Skin: THREE.MeshStandardMaterial;
    Pants: THREE.MeshStandardMaterial;
    Eyes: THREE.MeshStandardMaterial;
    Socks: THREE.MeshStandardMaterial;
    Hair: THREE.MeshStandardMaterial;
  };
};
const keyboardMap = [
  { name: "forward", keys: ["ArrowUp", "KeyW"] },
  { name: "backward", keys: ["ArrowDown", "KeyS"] },
  { name: "leftward", keys: ["ArrowLeft", "KeyA"] },
  { name: "rightward", keys: ["ArrowRight", "KeyD"] },
  { name: "jump", keys: ["Space"] },
  { name: "run", keys: ["Shift"] },
  { name: "action1", keys: ["1"] },
  { name: "action2", keys: ["2"] },
  { name: "action3", keys: ["3"] },
  { name: "action4", keys: ["KeyF"] },
];
type ActionName =
  | "HumanArmature|Man_Clapping"
  | "HumanArmature|Man_Death"
  | "HumanArmature|Man_Idle"
  | "HumanArmature|Man_Jump"
  | "HumanArmature|Man_Punch"
  | "HumanArmature|Man_Run"
  | "HumanArmature|Man_RunningJump"
  | "HumanArmature|Man_Sitting"
  | "HumanArmature|Man_Standing"
  | "HumanArmature|Man_SwordSlash"
  | "HumanArmature|Man_Walk";

const animationSet: Record<string, ActionName> = {
  idle: "HumanArmature|Man_Idle",
  walk: "HumanArmature|Man_Walk",
  run: "HumanArmature|Man_Run",
  jump: "HumanArmature|Man_Jump",
  jumpIdle: "HumanArmature|Man_RunningJump",
  jumpLand: "HumanArmature|Man_Standing",
  fall: "HumanArmature|Man_Sitting", // This is for falling from high sky
  action1: "HumanArmature|Man_Clapping",
  action2: "HumanArmature|Man_Death",
  action3: "HumanArmature|Man_SwordSlash",
};

export function Hero(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials } = useGLTF("/Man.glb") as GLTFResult;
  return (
    <KeyboardControls map={keyboardMap}>
      <Ecctrl rayHitForgiveness={0} debug animated>
        <EcctrlAnimation characterURL={"/Man.glb"} animationSet={animationSet}>
          <group
            position={[0, -0.7, 0]}
            ref={group}
            {...props}
            scale={[0.4, 0.4, 0.4]}
            dispose={null}
          >
            <group name="Root_Scene">
              <group name="RootNode">
                <group
                  name="HumanArmature"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <primitive object={nodes.Bone} />
                </group>
                <group
                  name="BaseHuman"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <skinnedMesh
                    name="BaseHuman_1"
                    geometry={nodes.BaseHuman_1.geometry}
                    material={materials.Shirt}
                    skeleton={nodes.BaseHuman_1.skeleton}
                  />
                  <skinnedMesh
                    name="BaseHuman_2"
                    geometry={nodes.BaseHuman_2.geometry}
                    material={materials.Skin}
                    skeleton={nodes.BaseHuman_2.skeleton}
                  />
                  <skinnedMesh
                    name="BaseHuman_3"
                    geometry={nodes.BaseHuman_3.geometry}
                    material={materials.Pants}
                    skeleton={nodes.BaseHuman_3.skeleton}
                  />
                  <skinnedMesh
                    name="BaseHuman_4"
                    geometry={nodes.BaseHuman_4.geometry}
                    material={materials.Eyes}
                    skeleton={nodes.BaseHuman_4.skeleton}
                  />
                  <skinnedMesh
                    name="BaseHuman_5"
                    geometry={nodes.BaseHuman_5.geometry}
                    material={materials.Socks}
                    skeleton={nodes.BaseHuman_5.skeleton}
                  />
                  <skinnedMesh
                    name="BaseHuman_6"
                    geometry={nodes.BaseHuman_6.geometry}
                    material={materials.Hair}
                    skeleton={nodes.BaseHuman_6.skeleton}
                  />
                </group>
              </group>
            </group>
          </group>
        </EcctrlAnimation>
      </Ecctrl>
    </KeyboardControls>
  );
}

useGLTF.preload("/Man.glb");
